// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tctderzpbrbtatprpmna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdGRlcnpwYnJidGF0cHJwbW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDAzMDMsImV4cCI6MjA2NzU3NjMwM30.azTg_bOs-E9WShGFBtiRFWV8wGekXMXq83BzASh-rVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});